### PR TITLE
Add snpEff to MALVIRUS pipeline

### PR DESCRIPTION
**Pull request by mpre**
- Add snpEff to conda environment
- Add snpEff step to the snakemake pipeline
- Add a step to "clean" the vcf output by malva
  (i.e., remove unused ALTs entries that will break snpEff)
- Update GenotypeTable.jsx to report the effect of SNPs

### CODE REVIEW

**Comment by mpre** [comment]
@yp please check that I didn't break something in GenotypeTable.jsx.  Locally everything runs fine.

**Comment by yp** [comment]
I extended the report table to open a modal with all the info computed by snpEff.
@AlgoLab/malvirus Please, have a look.

**Comment by yp** [comment]
What happens if data is not from SARS-CoV-2?

**Comment by yp** [comment]
TODO:

- [ ] Update backend code and/or json produced by the Snakefile to present the new output files
- [ ] Update documentation

**Comment by mpre** [comment]
> I extended the report table to open a modal with all the info computed by snpEff.
> @AlgoLab/malvirus Please, have a look.

I really like it!

> What happens if data is not from SARS-CoV-2?

If [refname](https://github.com/AlgoLab/MALVIRUS/blob/b51f254e4d364244a109bb5ffcd6551ef3c5847f/snakemake/Snakefile.malva#L29) is set in the config file, then the db of that reference will be used.

We should update the backend and the frontend to reflect it and give the user the option to not run snpEff.
We can also extract this info from the fasta header of the reference file, but I'm pretty sure it will break MALVIRUS most of the time.

**Comment by yp** [comment]
> > What happens if data is not from SARS-CoV-2?
> 
> If [refname](https://github.com/AlgoLab/MALVIRUS/blob/b51f254e4d364244a109bb5ffcd6551ef3c5847f/snakemake/Snakefile.malva#L29) is set in the config file, then the db of that reference will be used.
> 
> We should update the backend and the frontend to reflect it and give the user the option to not run snpEff.
> We can also extract this info from the fasta header of the reference file, but I'm pretty sure it will break MALVIRUS most of the time.

What about adding a catalog of common references (starting from SARS-CoV-2)? The user can either upload a FASTA and a VCF or choose an existing reference. In that way we know if we can run snpEff or not.

**Comment by yp** [comment]
I added the directory `refs` in commit Algolab/MALVIRUS-data@7b85357af29f60e37cb0ea23a532bd2d9ab97aaf with the genomic references already known to MALVIRUS (only SARS-CoV2-2, now). If the user uploads or creates a new catalog based on one of those references, then `snpEff` is also executed, otherwise that step is skipped.
@AlgoLab/malvirus what do you think about that? Could you perform some tests, please?

**Review by yp — COMMENTED** [review]
LGTM (of course)

**Comment by yp** [comment]
I've just modified the documentation including SnpEff. Unless someone spots an error, I will merge to master and I will prepare a new release.

**Review by yp — APPROVED** [review]
As per internal communication, the changes have been approved.

**Pull request merged**
